version: "3.7"
services:
  nginx:
    image: nginx:1.16.0-alpine
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host    
      - target: 443
        published: 8443
        protocol: tcp
        mode: host      
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./certs/tls.crt:/etc/nginx/tls.crt
      - ./certs/tls.key:/etc/nginx/tls.key

      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql:8.0.16
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql_data:/var/lib/mysql
    
  mirror:
    build: ./py-request-mirror
    environment:
      PORT: 5000
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host    
